<?php

declare(strict_types=1);

namespace App\Services\Domain;

use App\Support\Domain\Constants;
use App\Support\Domain\Helpers;

final class SeedStateFactory
{
    /**
     * @return array<string,mixed>
     */
    public static function make(): array
    {
        $now = Helpers::nowIso();
        $startDate = (new \DateTimeImmutable('first day of this month 00:00:00'))->modify('+4 day')->format('Y-m-d');
        $dueDate = Helpers::cycleDueDate($startDate, 1);

        $adminSalt = Helpers::uid('salt');
        $leaderSalt = Helpers::uid('salt');
        $memberSalt = Helpers::uid('salt');
        $pendingSalt = Helpers::uid('salt');

        $admin = [
            'id' => 'usr_admin',
            'fullName' => 'Platform Admin',
            'email' => 'admin@susukonnect.app',
            'phone' => '+15550000001',
            'role' => 'admin',
            'passwordHash' => Helpers::hashPassword('Admin@2026', $adminSalt),
            'salt' => $adminSalt,
            'acceptedTerms' => true,
            'verifiedBadge' => true,
            'biometricEnabled' => false,
            'mfaEnabled' => true,
            'status' => 'active',
            'knownDevices' => [],
            'paymentMethods' => [],
            'metrics' => [
                'paidContributions' => 0,
                'completedGroups' => 0,
                'internalTrustScore' => 82,
            ],
            'kyc' => [
                'status' => 'verified',
                'idType' => 'Passport',
                'idNumberToken' => Helpers::tokenRef('admin-id'),
                'dob' => '1990-01-01',
                'selfieToken' => Helpers::tokenRef('admin-selfie'),
                'addressToken' => Helpers::tokenRef('admin-address'),
                'submittedAt' => $now,
            ],
            'createdAt' => $now,
        ];

        $leader = [
            'id' => 'usr_leader',
            'fullName' => 'Aisha Leader',
            'email' => 'leader@susukonnect.app',
            'phone' => '+15550000002',
            'role' => 'leader',
            'passwordHash' => Helpers::hashPassword('Leader@2026', $leaderSalt),
            'salt' => $leaderSalt,
            'acceptedTerms' => true,
            'verifiedBadge' => true,
            'biometricEnabled' => true,
            'mfaEnabled' => true,
            'status' => 'active',
            'knownDevices' => [],
            'paymentMethods' => [
                [
                    'id' => 'pm_leader_main',
                    'type' => 'bank',
                    'label' => 'Primary ACH',
                    'last4' => '1008',
                    'tokenRef' => 'pm_1Q0000000000LeaderACH',
                    'autoDebit' => true,
                    'createdAt' => $now,
                ],
            ],
            'metrics' => [
                'paidContributions' => 4,
                'completedGroups' => 1,
                'internalTrustScore' => 88,
            ],
            'kyc' => [
                'status' => 'verified',
                'idType' => "Driver's License",
                'idNumberToken' => Helpers::tokenRef('leader-id'),
                'dob' => '1993-03-20',
                'selfieToken' => Helpers::tokenRef('leader-selfie'),
                'addressToken' => Helpers::tokenRef('leader-address'),
                'submittedAt' => $now,
            ],
            'createdAt' => $now,
        ];

        $member = [
            'id' => 'usr_member',
            'fullName' => 'Samuel Member',
            'email' => 'member@susukonnect.app',
            'phone' => '+15550000003',
            'role' => 'member',
            'passwordHash' => Helpers::hashPassword('Member@2026', $memberSalt),
            'salt' => $memberSalt,
            'acceptedTerms' => true,
            'verifiedBadge' => true,
            'biometricEnabled' => false,
            'mfaEnabled' => true,
            'status' => 'active',
            'knownDevices' => [],
            'paymentMethods' => [
                [
                    'id' => 'pm_member_debit',
                    'type' => 'debit',
                    'label' => 'Family Debit',
                    'last4' => '4455',
                    'tokenRef' => 'pm_1Q0000000000MemberDebit',
                    'autoDebit' => false,
                    'createdAt' => $now,
                ],
            ],
            'metrics' => [
                'paidContributions' => 3,
                'completedGroups' => 1,
                'internalTrustScore' => 79,
            ],
            'kyc' => [
                'status' => 'verified',
                'idType' => 'Passport',
                'idNumberToken' => Helpers::tokenRef('member-id'),
                'dob' => '1995-07-11',
                'selfieToken' => Helpers::tokenRef('member-selfie'),
                'addressToken' => Helpers::tokenRef('member-address'),
                'submittedAt' => $now,
            ],
            'createdAt' => $now,
        ];

        $pendingUser = [
            'id' => 'usr_pending',
            'fullName' => 'New Applicant',
            'email' => 'applicant@susukonnect.app',
            'phone' => '+15550000004',
            'role' => 'member',
            'passwordHash' => Helpers::hashPassword('Member@2026', $pendingSalt),
            'salt' => $pendingSalt,
            'acceptedTerms' => true,
            'verifiedBadge' => false,
            'biometricEnabled' => false,
            'mfaEnabled' => true,
            'status' => 'active',
            'knownDevices' => [],
            'paymentMethods' => [],
            'metrics' => [
                'paidContributions' => 0,
                'completedGroups' => 0,
                'internalTrustScore' => 52,
            ],
            'kyc' => [
                'status' => 'pending',
                'idType' => 'National ID',
                'idNumberToken' => Helpers::tokenRef('pending-id'),
                'dob' => '1999-10-10',
                'selfieToken' => Helpers::tokenRef('pending-selfie'),
                'addressToken' => Helpers::tokenRef('pending-address'),
                'submittedAt' => $now,
            ],
            'createdAt' => $now,
        ];

        $fixedGroup = [
            'id' => 'grp_fixed_001',
            'inviteCode' => 'JOINFIXED01',
            'name' => 'Diaspora Family Circle',
            'description' => 'Monthly fixed-rotation savings circle.',
            'communityType' => 'West African Diaspora',
            'location' => 'New York',
            'startDate' => $startDate,
            'contributionAmount' => 200.0,
            'currency' => 'USD',
            'totalMembers' => 5,
            'payoutFrequency' => 'monthly',
            'payoutOrderLogic' => 'fixed',
            'gracePeriodDays' => 3,
            'requiresLeaderApproval' => true,
            'rules' => 'Contributions due by the 5th each month.',
            'leaderId' => $leader['id'],
            'memberIds' => [$leader['id'], $member['id']],
            'joinRequests' => [$pendingUser['id']],
            'payoutOrder' => [$leader['id'], $member['id']],
            'cycle' => 1,
            'status' => 'active',
            'chatArchived' => false,
            'createdAt' => $now,
        ];

        $votingGroup = [
            'id' => 'grp_vote_001',
            'inviteCode' => 'JOINVOTE01',
            'name' => 'Community Growth Pot',
            'description' => 'Voting-based payout circle.',
            'communityType' => 'Caribbean Entrepreneurs',
            'location' => 'Toronto',
            'startDate' => $startDate,
            'contributionAmount' => 150.0,
            'currency' => 'USD',
            'totalMembers' => 4,
            'payoutFrequency' => 'monthly',
            'payoutOrderLogic' => 'voting',
            'gracePeriodDays' => 4,
            'requiresLeaderApproval' => false,
            'rules' => 'One vote per member each cycle.',
            'leaderId' => $leader['id'],
            'memberIds' => [$leader['id'], $member['id']],
            'joinRequests' => [],
            'payoutOrder' => [$leader['id'], $member['id']],
            'cycle' => 1,
            'status' => 'active',
            'chatArchived' => false,
            'createdAt' => $now,
        ];

        $priorityGroup = [
            'id' => 'grp_priority_001',
            'inviteCode' => 'JOINPRIO01',
            'name' => 'Emergency Shield Circle',
            'description' => 'Priority-weighted payout circle.',
            'communityType' => 'General',
            'location' => 'London',
            'startDate' => $startDate,
            'contributionAmount' => 180.0,
            'currency' => 'GBP',
            'totalMembers' => 3,
            'payoutFrequency' => 'monthly',
            'payoutOrderLogic' => 'priority',
            'gracePeriodDays' => 2,
            'requiresLeaderApproval' => true,
            'rules' => 'Priority reasons score recipient eligibility.',
            'leaderId' => $leader['id'],
            'memberIds' => [$leader['id'], $member['id']],
            'joinRequests' => [],
            'payoutOrder' => [$member['id'], $leader['id']],
            'cycle' => 1,
            'status' => 'active',
            'chatArchived' => false,
            'createdAt' => $now,
        ];

        return [
            'users' => [$admin, $leader, $member, $pendingUser],
            'groups' => [$fixedGroup, $votingGroup, $priorityGroup],
            'contributions' => [
                [
                    'id' => 'ctr_fix_leader',
                    'groupId' => $fixedGroup['id'],
                    'cycle' => 1,
                    'userId' => $leader['id'],
                    'amount' => 200.0,
                    'dueDate' => $dueDate,
                    'status' => 'paid',
                    'methodId' => 'pm_leader_main',
                    'methodType' => 'bank',
                    'autoDebit' => true,
                    'providerReference' => 'seed_ref_leader_fixed',
                    'paidAt' => $now,
                    'createdAt' => $now,
                ],
                [
                    'id' => 'ctr_fix_member',
                    'groupId' => $fixedGroup['id'],
                    'cycle' => 1,
                    'userId' => $member['id'],
                    'amount' => 200.0,
                    'dueDate' => $dueDate,
                    'status' => 'pending',
                    'autoDebit' => false,
                    'createdAt' => $now,
                ],
                [
                    'id' => 'ctr_vote_leader',
                    'groupId' => $votingGroup['id'],
                    'cycle' => 1,
                    'userId' => $leader['id'],
                    'amount' => 150.0,
                    'dueDate' => $dueDate,
                    'status' => 'paid',
                    'methodId' => 'pm_leader_main',
                    'methodType' => 'bank',
                    'autoDebit' => true,
                    'providerReference' => 'seed_ref_leader_vote',
                    'paidAt' => $now,
                    'createdAt' => $now,
                ],
                [
                    'id' => 'ctr_vote_member',
                    'groupId' => $votingGroup['id'],
                    'cycle' => 1,
                    'userId' => $member['id'],
                    'amount' => 150.0,
                    'dueDate' => $dueDate,
                    'status' => 'paid',
                    'methodId' => 'pm_member_debit',
                    'methodType' => 'debit',
                    'autoDebit' => false,
                    'providerReference' => 'seed_ref_member_vote',
                    'paidAt' => $now,
                    'createdAt' => $now,
                ],
                [
                    'id' => 'ctr_prio_leader',
                    'groupId' => $priorityGroup['id'],
                    'cycle' => 1,
                    'userId' => $leader['id'],
                    'amount' => 180.0,
                    'dueDate' => $dueDate,
                    'status' => 'paid',
                    'methodId' => 'pm_leader_main',
                    'methodType' => 'bank',
                    'autoDebit' => true,
                    'providerReference' => 'seed_ref_leader_prio',
                    'paidAt' => $now,
                    'createdAt' => $now,
                ],
                [
                    'id' => 'ctr_prio_member',
                    'groupId' => $priorityGroup['id'],
                    'cycle' => 1,
                    'userId' => $member['id'],
                    'amount' => 180.0,
                    'dueDate' => $dueDate,
                    'status' => 'paid',
                    'methodId' => 'pm_member_debit',
                    'methodType' => 'debit',
                    'autoDebit' => false,
                    'providerReference' => 'seed_ref_member_prio',
                    'paidAt' => $now,
                    'createdAt' => $now,
                ],
            ],
            'payouts' => [
                [
                    'id' => 'pay_prio_001',
                    'groupId' => $priorityGroup['id'],
                    'cycle' => 1,
                    'recipientId' => $member['id'],
                    'amount' => 360.0,
                    'currency' => 'GBP',
                    'reason' => 'Medical procedure',
                    'status' => 'requested',
                    'requestedAt' => $now,
                    'reasonReviewStatus' => 'approved',
                    'reasonReviewedBy' => $leader['id'],
                    'reasonReviewedAt' => $now,
                    'leaderApprovedBy' => $leader['id'],
                    'recipientMfaConfirmed' => false,
                    'platformFee' => 0.0,
                    'netAmount' => 0.0,
                ],
            ],
            'payoutVotes' => [
                [
                    'id' => 'vote_seed_001',
                    'groupId' => $votingGroup['id'],
                    'cycle' => 1,
                    'voterId' => $leader['id'],
                    'candidateId' => $member['id'],
                    'note' => 'Business investment priority',
                    'createdAt' => $now,
                ],
            ],
            'priorityClaims' => [
                [
                    'id' => 'claim_seed_001',
                    'groupId' => $priorityGroup['id'],
                    'cycle' => 1,
                    'userId' => $member['id'],
                    'reason' => 'Medical procedure',
                    'customReason' => 'Surgery co-pay',
                    'weight' => Constants::PRIORITY_WEIGHTS['Medical procedure'],
                    'createdAt' => $now,
                ],
            ],
            'chats' => [
                [
                    'id' => 'msg_seed_001',
                    'groupId' => $fixedGroup['id'],
                    'userId' => $leader['id'],
                    'content' => 'Welcome to the circle. Contributions are due on the 5th.',
                    'type' => 'announcement',
                    'pinned' => true,
                    'createdAt' => $now,
                ],
                [
                    'id' => 'msg_seed_002',
                    'groupId' => $fixedGroup['id'],
                    'userId' => $member['id'],
                    'content' => 'Thanks. I will pay before grace deadline.',
                    'type' => 'message',
                    'pinned' => false,
                    'createdAt' => $now,
                ],
            ],
            'notifications' => [
                [
                    'id' => 'note_seed_001',
                    'userId' => $member['id'],
                    'title' => 'Contribution reminder',
                    'body' => 'Your contribution for Diaspora Family Circle is pending.',
                    'type' => 'reminder',
                    'dedupeKey' => 'seed-reminder',
                    'read' => false,
                    'createdAt' => $now,
                ],
            ],
            'disputes' => [],
            'fraudFlags' => [],
            'auditLogs' => [
                [
                    'id' => Helpers::uid('audit'),
                    'actorId' => $admin['id'],
                    'action' => 'SEED_PLATFORM_READY',
                    'targetType' => 'system',
                    'targetId' => 'seed',
                    'metadata' => [],
                    'timestamp' => $now,
                    'previousHash' => 'GENESIS',
                    'entryHash' => Helpers::hashValue('GENESIS|' . $now . '|' . $admin['id'] . '|SEED_PLATFORM_READY|system|seed|{}'),
                ],
            ],
            'sessions' => [],
            'mfaChallenges' => [],
            'authControls' => [
                'loginAttempts' => [],
            ],
            'meta' => [
                'platformFeeRate' => (float) env('PLATFORM_FEE_RATE', 0.015),
                'adminPayoutApprovalThreshold' => (float) env('ADMIN_PAYOUT_APPROVAL_THRESHOLD', 2000),
            ],
        ];
    }
}
